export const xrayData = [
  { id: 1, Exam: "Abdomen Lateral", Price: 594 },
  { id: 2, Exam: "Abdomen Lateral Decubitus", Price: 665 },
  { id: 3, Exam: "Abdomen Supine", Price: 594 },
  { id: 4, Exam: "Ankle Joint AP", Price: 396 },
  { id: 5, Exam: "Ankle Joint APL/Mortise", Price: 600 },
  { id: 6, Exam: "Ankle Joint APL - Bilateral", Price: 962 },
  { id: 7, Exam: "Babygram", Price: 869 },
  { id: 8, Exam: "Calcaneus APL", Price: 1034 },
  { id: 9, Exam: "Calcaneus AP - Bilateral", Price: 792 },
  { id: 10, Exam: "Calcaneus AP - Unilateral", Price: 583 },
  { id: 11, Exam: "Cervical APL", Price: 792 },
  { id: 12, Exam: "Cevical APL and both Obliques", Price: 858 },
  { id: 13, Exam: "Cevicothoracic APL", Price: 902 },
  { id: 14, Exam: "Chest Bucky AP", Price: 539 },
  { id: 15, Exam: "Chest Bucky AP and Obliques", Price: 858 },
  { id: 16, Exam: "Chest Lateral Decubitus", Price: 285 },
  { id: 17, Exam: "Chest PA and Apicolordotic", Price: 533 },
  { id: 18, Exam: "Chest PA/AP", Price: 285 },
  { id: 19, Exam: "Chest PAL/APL", Price: 489 },
  { id: 20, Exam: "Clavicle AP/Angulated", Price: 583 },
  { id: 21, Exam: "Cystography", Price: 1078 },
  { id: 22, Exam: "Elbow Joint APL", Price: 583 },
  { id: 23, Exam: "Elbow Joint APL - Bilateral", Price: 1034 },
  { id: 24, Exam: "Foot APO/APL - Bilateral", Price: 583 },
  { id: 25, Exam: "Thigh AP", Price: 530 },
  { id: 26, Exam: "Thigh APL", Price: 800 },
  { id: 27, Exam: "Thigh APL Bilateral", Price: 970 },
  { id: 28, Exam: "Fetogram", Price: 583 },
  { id: 29, Exam: "Foot APO/APL", Price: 530 },
  { id: 30, Exam: "Foot APOL", Price: 759 },
  { id: 31, Exam: "Foot APOL - Bilateral", Price: 1034 },
  { id: 32, Exam: "Forearm APL", Price: 583 },
  { id: 33, Exam: "Hand APL/APO - Bilateral", Price: 1034 },
  { id: 34, Exam: "Hand APOL", Price: 690 },
  { id: 35, Exam: "Hip Joint Crosstable Lateral", Price: 605 },
  { id: 36, Exam: "Arm AP", Price: 450 },
  { id: 37, Exam: "Arm APL", Price: 650 },
  { id: 38, Exam: "Knee Joint AP", Price: 369 },
  { id: 39, Exam: "Knee Joint APL", Price: 583 },
  { id: 40, Exam: "Knee Joint APL - Bilateral", Price: 880 },
  { id: 41, Exam: "KUB Xray", Price: 473 },
  { id: 42, Exam: "Leg AP", Price: 418 },
  { id: 43, Exam: "Leg APL", Price: 627 },
  { id: 44, Exam: "Leg APL - Bilateral", Price: 1067 },
  { id: 45, Exam: "Lumbar AP", Price: 583 },
  { id: 46, Exam: "Lumbar APL", Price: 858 },
  { id: 47, Exam: "Lumbosacral AP", Price: 594 },
  { id: 48, Exam: "Lumbosacral APL", Price: 891 },
  { id: 49, Exam: "Lumbosacral APL and Obliques", Price: 1100 },
  { id: 50, Exam: "Odontoid Process APL/Open Mouth", Price: 462 },
  { id: 51, Exam: "Operative Cholangiography", Price: 1430 },
  { id: 52, Exam: "Pelvis AP", Price: 594 },
  { id: 53, Exam: "Pelvis AP and Obliques", Price: 891 },
  { id: 54, Exam: "Pelvis APL", Price: 660 },
  { id: 55, Exam: "Sacrococcyx APL", Price: 583 },
  { id: 56, Exam: "Shoulder APY", Price: 418 },
  { id: 57, Exam: "Shoulder APY - Bilateral", Price: 605 },
  { id: 58, Exam: "Skeletal Survey", Price: 2600 },
  { id: 59, Exam: "Thoracic AP", Price: 583 },
  { id: 60, Exam: "Thoracic APL", Price: 792 },
  { id: 61, Exam: "Thoracic APL and Obliques", Price: 1001 },
  { id: 62, Exam: "Thoracolumbar AP", Price: 902 },
  { id: 63, Exam: "Thoracolumbar APL", Price: 1034 },
  { id: 64, Exam: "Voiding Cystourethrogram", Price: 1540 },
  {
    id: 65,
    Exam: "Voiding Cystourethrogram - Pediatrics",
    Price: 1500,
  },
  { id: 66, Exam: "Wrist APL/APO - Bilateral", Price: 880 },
  { id: 67, Exam: "Basal View Skull/ Submentovertex", Price: 770 },
  { id: 68, Exam: "Skull AP", Price: 451 },
  { id: 69, Exam: "Skull APL", Price: 676 },
  { id: 70, Exam: "Nasal Bone Soft Tissue Lateral", Price: 462 },
  { id: 71, Exam: "Mandible PA", Price: 440 },
  { id: 72, Exam: "Mandible PA and Oblique", Price: 693 },
  { id: 73, Exam: "Neck Soft Tissue Lateral", Price: 539 },
  { id: 74, Exam: "Chest Apicolordotic View", Price: 533 },
  { id: 75, Exam: "Abdomen Supine and Upright", Price: 891 },
  { id: 76, Exam: "Abdomen Upright", Price: 594 },
  { id: 77, Exam: "Paranasal Sinus APL and Waters", Price: 918 },
  {
    id: 78,
    Exam: "Skull Series (AP, Lateral, Waters/Townes/Caldwells)",
    Price: 918,
  },
  { id: 79, Exam: "Waters (Parietoacanthial", Price: 467 },
  { id: 80, Exam: "Caldwells (PA AXIAL)", Price: 467 },
  { id: 81, Exam: "Townes (AP AXIAL)", Price: 467 },
  { id: 82, Exam: "Pelvis AP & HIP Crosstable Lateral", Price: 1069 },
  { id: 83, Exam: "T-Tube Cholangiogram", Price: 1045 },
  { id: 84, Exam: "Fistulogram", Price: 950 },
  { id: 85, Exam: "Mandible Series", Price: 835 },
  { id: 86, Exam: "Forearm AP", Price: 360 },
  { id: 87, Exam: "Elbow Joint AP", Price: 360 },
  { id: 88, Exam: "Forearm APL Bilateral", Price: 780 },
  { id: 89, Exam: "Clavicle AP/Angulated Bilateral", Price: 550 },
  { id: 90, Exam: "Thigh AP Bilateral", Price: 800 },
  { id: 91, Exam: "Forearm AP Bilateral", Price: 530 },
  { id: 92, Exam: "Hand AP", Price: 360 },
  { id: 93, Exam: "Hand AP Bilateral", Price: 780 },
  { id: 94, Exam: "Arm AP Bilateral", Price: 650 },
  { id: 95, Exam: "Arm APL Bilateral", Price: 800 },
  { id: 96, Exam: "Knee Joint AP Bilateral", Price: 530 },
  { id: 97, Exam: "Leg AP Bilateral", Price: 570 },
  { id: 98, Exam: "Wrist AP", Price: 360 },
  { id: 99, Exam: "Chest Lateral", Price: 250 },
  { id: 100, Exam: "RGP Unilateral", Price: 1650 },
  { id: 101, Exam: "RGP Bilateral", Price: 2090 },
];

export const orData = [
  { id: 1, Exam: "Abdomino-Perineal Preparation", Price: 250 },
  { id: 2, Exam: "Application of Cast", Price: 1500 },
  { id: 3, Exam: "Blood Pressure Taking", Price: 50 },
  { id: 4, Exam: "SS Enema", Price: 100 },
  { id: 5, Exam: "Dressing Fee", Price: 150 },
  { id: 6, Exam: "ECG 12 Leads", Price: 350 },
  { id: 7, Exam: "IV Infusion Fee", Price: 300 },
  { id: 8, Exam: "ECG Long Lead", Price: 150 },
  { id: 9, Exam: "ET Tube Insertion", Price: 500 },
  { id: 10, Exam: "Excision of Cyst Small", Price: 1000 },
  { id: 11, Exam: "Foley Catheter Insertion", Price: 300 },
  { id: 12, Exam: "Hot Sitz Bath", Price: 100 },
  { id: 13, Exam: "Incision and Drainage Small", Price: 1000 },
  { id: 14, Exam: "IE", Price: 50 },
  { id: 15, Exam: "Injection with Skin Test", Price: 65 },
  { id: 16, Exam: "Injection without Skin Test", Price: 50 },
  { id: 17, Exam: "IV Cutdown", Price: 2000 },
  { id: 18, Exam: "IV Insertion Adult", Price: 90 },
  { id: 19, Exam: "IV Insertion Pedia", Price: 120 },
  { id: 20, Exam: "NGT Insertion", Price: 500 },
  { id: 21, Exam: "Removal of Cast", Price: 1000 },
  { id: 22, Exam: "Removal of Foreign Body", Price: 1000 },
  { id: 23, Exam: "Removal of Ingrown", Price: 1000 },
  { id: 24, Exam: "Removal of Staples", Price: 150 },
  { id: 25, Exam: "Removal of Sutures", Price: 150 },
  { id: 26, Exam: "Suctioning ER Use", Price: 100 },
  { id: 27, Exam: "Suctioning Ward", Price: 150 },
  { id: 28, Exam: "Suturing Fee (10 Stitches & Below", Price: 1000 },
  { id: 29, Exam: "Suturing Set", Price: 150 },
  { id: 30, Exam: "Umbilical Catheterization", Price: 1000 },
  { id: 31, Exam: "Circumcision Fee", Price: 500 },
  { id: 32, Exam: "Debridement Small", Price: 1000 },
  { id: 33, Exam: "Intubation Fee", Price: 1500 },
  { id: 34, Exam: "Colostomy Care", Price: 200 },
  { id: 35, Exam: "Trancheostomy Care", Price: 200 },
  { id: 36, Exam: "SS Enema/Cleansing Enema", Price: 300 },
  { id: 37, Exam: "ECG 12 Leads with Reading", Price: 450 },
  { id: 38, Exam: "ECG Reading Fee", Price: 200 },
  { id: 39, Exam: "Ear Flushing", Price: 500 },
  { id: 40, Exam: "Close Reduction Fee", Price: 2000 },
  { id: 41, Exam: "Nephrostomy Tube Insertion", Price: 800 },
  { id: 42, Exam: "Suprapubic Cystostomy", Price: 1000 },
  { id: 43, Exam: "Paracentesis", Price: 2000 },
  { id: 44, Exam: "Paracentesis with Catheter", Price: 2500 },
  { id: 45, Exam: "Suprapubic Catheter Insertion", Price: 3000 },
  { id: 46, Exam: "Cystogram", Price: 1200 },
  { id: 47, Exam: "Removal of Skin Tag", Price: 1000 },
  { id: 48, Exam: "Thoracentesis", Price: 2000 },
  { id: 49, Exam: "Suturing Fee (more than 10 stitches)", Price: 1500 },
  { id: 50, Exam: "Debridement Medium", Price: 1500 },
  { id: 51, Exam: "Debridement Large", Price: 2000 },
  { id: 52, Exam: "Excision of Cyst Medium", Price: 1500 },
  { id: 53, Exam: "Excision of Cyst Large", Price: 2000 },
  { id: 54, Exam: "Fine Needle Aspiration", Price: 1500 },
  { id: 55, Exam: "I and D Bedside Small", Price: 1000 },
  { id: 56, Exam: "I and D Bedside Medium", Price: 1500 },
  { id: 57, Exam: "I and D Bedside Large", Price: 2000 },
  { id: 58, Exam: "Incision Biopsy", Price: 2000 },
  { id: 59, Exam: "Amputation of Digit/s", Price: 1500 },
  { id: 60, Exam: "Removal of Foley Catheter", Price: 150 },
  { id: 61, Exam: "Gastric Lavage", Price: 500 },
];

export const ultraData = [
  { id: 0, Exam: "Whole Abdomen", Price: 2050 },
  { id: 1, Exam: "Hemithoraces - Bilateral", Price: 1210 },
  { id: 2, Exam: "Hemithorax - Unilateral", Price: 850 },
  { id: 3, Exam: "Hemithoraces w/ mapping - Bilateral", Price: 1330 },
  { id: 4, Exam: "Hemithorax w/ mapping - Unilateral", Price: 970 },
  { id: 5, Exam: "Hepatobillary Tract and Pancreas", Price: 1020 },
  { id: 6, Exam: "KUB Prostate/Pelvis", Price: 1200 },
  { id: 7, Exam: "One Organ", Price: 850 },
  { id: 8, Exam: "Pelvis", Price: 850 },
  { id: 9, Exam: "Pelvis - OB", Price: 1020 },
  { id: 10, Exam: "Right Lower Quadrant", Price: 1150 },
  { id: 11, Exam: "Right Upper Quadrant", Price: 1150 },
  { id: 12, Exam: "Transvaginal - Gyne", Price: 850 },
  { id: 13, Exam: "Transvaginal - OB", Price: 850 },
  { id: 14, Exam: "Upper Abdomen", Price: 1450 },
  { id: 15, Exam: "Multiple Pregnancy (Additional)", Price: 200 },
  { id: 16, Exam: "Transrectal", Price: 770 },
  { id: 17, Exam: "Soft Tissue", Price: 490 },
  { id: 18, Exam: "Inguinal Scrotal", Price: 1210 },
];

export const opdData = [
  { id: 0, Exam: "OPD Consultation", Price: 400 },
  { id: 1, Exam: "OPD Consultation Follow Up", Price: 300 },
  { id: 2, Exam: "OPD Consultation Sunday", Price: 450 },
  { id: 3, Exam: "OPD Consultation After 5pm", Price: 450 },
  { id: 4, Exam: "Consultation Kidney Clinic", Price: 800 },
  { id: 5, Exam: "Follow Up Consultation Kidney Clinic", Price: 400 },
  { id: 6, Exam: "Kidney Consult (Prescription Issuance", Price: 200 },
];

export const leadersData = [
  {
    id: 0,
    Source: "/face2.png",
    Name: "Paolo Severino",
    Position: "CHAIRMAN, HOSPITAL BOARD",
  },
  {
    id: 1,
    Source: "/face.png",
    Name: "Dr. Ma. Jennifer Subong",
    Position: "MEDICAL DIRECTOR",
  },
  {
    id: 2,
    Source: "/face.png",
    Name: "May Anne G. Paguntalan, RN",
    Position: "O.I.C - ADMINISTRATIVE SERVICES",
  },
];

export const carouselData = [
  { id: 0, Source: "image1.jpg" },
  { id: 1, Source: "image2.jpg" },
  { id: 2, Source: "image3.jpg" },
  { id: 3, Source: "image4.jpg" },
  { id: 4, Source: "image5.jpg" },
];

export const contactData = [
  { id: 0, department: "Information", contactNum: "0344880868" },
  { id: 1, department: "Emergency", contactNum: "09381630291" },
  { id: 2, department: "Accounting", contactNum: "0342130001" },
  { id: 3, department: "Pharmacy", contactNum: "09158713567" }
];

export const roomsData = [
  {id: 0, source: "/services/ward.png", title: "Ward", rate: 900, amenities: ["3 Beds", "Fully Air Conditioned", "Restroom", "Visitor’s Chair"] },
  {id: 1, source: "/services/privateFan.png", title: "Private (Fan)", rate: 1000, amenities: ["2 Beds", "Fan Only", "Restroom", "Visitor’s Chair"] },
  {id: 2, source: "/services/privateSmall.jpg", title: "Private Small", rate: 2500, amenities: ["1 Bed", "Fully Air Conditioned", "TV", "Restroom", "Visitor’s Chair"] },
  {id: 2, source: "/services/privateBig.jpg", title: "Private Big", rate: 1450, amenities: ["2 Bed", "Fully Air Conditioned", "TV", "Restroom", "Visitor’s Chair"] },
  {id: 2, source: "/services/suite.jpg", title: "Suite", rate: 2800, amenities: ["1 Bed", "Fully Air Conditioned", "TV", "Refrigerator", "Restroom", "Visitor’s Chair"] }
];

export const doctorsData = [
  {
    id: 0,
    Source: "/doctor1.jpg",
    Name: "DEAN CYRILLE CATOT",
    Position: "Surgery",
  },
  {
    id: 1,
    Source: "/doctor2.jpg",
    Name: "JEAN AIRENE GEROSO",
    Position: "Pediatrics",
  },
  {
    id: 2,
    Source: "/doctor3.jpg",
    Name: "Elanie morong",
    Position: "Pediatrics",
  },
  {
    id: 3,
    Source: "/doctor4.jpg",
    Name: "Joed Tan",
    Position: "Surgery",
  },
  {
    id: 4,
    Source: "/doctor5.jpg",
    Name: "EDILBERTO GO",
    Position: "Surgery",
  },
  {
    id: 5,
    Source: "/doctor6.jpg",
    Name: "Ma. Jennifer Subong",
    Position: "Pediatrics",
  },
  {
    id: 6,
    Source: "/doctor7.jpg",
    Name: "Almera Abapo",
    Position: "Obstetrics & Gynecology",
  },
  {
    id: 7,
    Source: "/doctor8.jpg",
    Name: "Peter Paul Hinolan",
    Position: "Internal Medicine",
  },
  {
    id: 8,
    Source: "/doctor9.jpg",
    Name: "Louie Corgos",
    Position: "Internal Medicine",
  },
  {
    id: 9,
    Source: "/doctor10.jpg",
    Name: "Ma. Rhodora Vaflor",
    Position: "Pediatrics",
  },
  {
    id: 10,
    Source: "/doctor11.jpg",
    Name: "May Flor Hinolan",
    Position: "Internal Medicine",
  },
  {
    id: 11,
    Source: "/doctor12.jpg",
    Name: "JAMES RAFAEL E. BILBAO",
    Position: "Pediatrics",
  },
  {
    id: 12,
    Source: "/doctor13.jpg",
    Name: "Oscar De Juan",
    Position: "Anesthesiology",
  },
  {
    id: 13,
    Source: "/doctor14.jpg",
    Name: "Anna Carmela Magallanes",
    Position: "Obstetrics & Gynecology",
  },
  {
    id: 14,
    Source: "/doctor15.jpg",
    Name: "Ernest Stephen Co",
    Position: "Surgery",
  },
  {
    id: 15,
    Source: "/doctor16.jpg",
    Name: "Laarni Guanzon",
    Position: "Internal Medicine",
  },
  {
    id: 16,
    Source: "/doctor17.jpg",
    Name: "AIRA JOY CO",
    Position: "Internal Medicine",
  },
  {
    id: 17,
    Source: "/doctor18.jpg",
    Name: "ARNEL EARL B. BATAYOLA",
    Position: "General Practitioner",
  },
  {
    id: 18,
    Source: "/doctor.jpg",
    Name: "ANNALYN L. VASQUEZ",
    Position: "Obstetrics & Gynecology",
  },
  {
    id: 19,
    Source: "/doctor19.jpg",
    Name: "Mario John Judith",
    Position: "Anesthesiology",
  },
];
